### ISSUE TITLE
Failed to delete

### ISSUE THREAD

**Issue by Fs2qFtoS** [eth-sri/sven#3]
Hi，May I ask is this the normal output? or the file is locked or something that I need to fix.

Would you mind give me some suggestions?

`A fatal error occurred: Error while recursively deleting '/experiments/sec_eval/sec-eval-350m-prefix/trained/cwe-089/0-py/sec_codeql_db/trap'
(eventual cause: MultiIOException "java.io.IOException: Failed to delete /......`

**Comment by LostBenjamin** [comment]
Hi, this looks like a problem with CodeQL or file permision issues on your operating system. I suggest to try to fix the issue in those directions.
